name: Run Main Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Set up environment variables from GitHub Secrets
      env:
        REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
        REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
        REDSHIFT_DBNAME: ${{ secrets.REDSHIFT_DBNAME }}
        REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
        REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python3 ./src/main_pipeline.py